/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CircleView = IDL.Record({
  'creator' : IDL.Principal,
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const Vibe = IDL.Record({
  'id' : IDL.Nat,
  'songTitle' : IDL.Text,
  'mood' : IDL.Text,
  'user' : IDL.Principal,
  'message' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'artistName' : IDL.Text,
});
export const MoodSong = IDL.Record({
  'id' : IDL.Nat,
  'mood' : IDL.Text,
  'title' : IDL.Text,
  'artist' : IDL.Text,
  'videoId' : IDL.Text,
  'addedBy' : IDL.Principal,
  'timestamp' : Time,
});
export const Profile = IDL.Record({ 'bio' : IDL.Text, 'username' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'registerCaller' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCircle' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteCircle' : IDL.Func([IDL.Text], [], []),
  'deleteVibe' : IDL.Func([IDL.Nat], [], []),
  'getAllCircles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, CircleView))],
      ['query'],
    ),
  'getAllVibes' : IDL.Func([], [IDL.Vec(Vibe)], ['query']),
  'getCallerProfile' : IDL.Func([], [Profile], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCircleMembers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getUserVibes' : IDL.Func([IDL.Principal], [IDL.Vec(Vibe)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinCircle' : IDL.Func([IDL.Text], [], []),
  'leaveCircle' : IDL.Func([IDL.Text], [], []),
  'postVibe' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addMoodSong' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'getMoodSongs' : IDL.Func([IDL.Text], [IDL.Vec(MoodSong)], ['query']),
  'deleteMoodSong' : IDL.Func([IDL.Nat], [], []),
  'getPublicUsername' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CircleView = IDL.Record({
    'creator' : IDL.Principal,
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Time = IDL.Int;
  const Vibe = IDL.Record({
    'id' : IDL.Nat,
    'songTitle' : IDL.Text,
    'mood' : IDL.Text,
    'user' : IDL.Principal,
    'message' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'artistName' : IDL.Text,
  });
  const MoodSong = IDL.Record({
    'id' : IDL.Nat,
    'mood' : IDL.Text,
    'title' : IDL.Text,
    'artist' : IDL.Text,
    'videoId' : IDL.Text,
    'addedBy' : IDL.Principal,
    'timestamp' : Time,
  });
  const Profile = IDL.Record({ 'bio' : IDL.Text, 'username' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'registerCaller' : IDL.Func([], [], []),
    'createCircle' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteCircle' : IDL.Func([IDL.Text], [], []),
    'deleteVibe' : IDL.Func([IDL.Nat], [], []),
    'getAllCircles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, CircleView))],
        ['query'],
      ),
    'getAllVibes' : IDL.Func([], [IDL.Vec(Vibe)], ['query']),
    'getCallerProfile' : IDL.Func([], [Profile], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCircleMembers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getUserVibes' : IDL.Func([IDL.Principal], [IDL.Vec(Vibe)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinCircle' : IDL.Func([IDL.Text], [], []),
    'leaveCircle' : IDL.Func([IDL.Text], [], []),
    'postVibe' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addMoodSong' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'getMoodSongs' : IDL.Func([IDL.Text], [IDL.Vec(MoodSong)], ['query']),
    'deleteMoodSong' : IDL.Func([IDL.Nat], [], []),
    'getPublicUsername' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
