/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CircleView {
  'creator' : Principal,
  'members' : Array<Principal>,
  'name' : string,
  'description' : string,
}
export interface Profile { 'bio' : string, 'username' : string }
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vibe {
  'id' : bigint,
  'songTitle' : string,
  'mood' : string,
  'user' : Principal,
  'message' : [] | [string],
  'timestamp' : Time,
  'artistName' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'registerCaller' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCircle' : ActorMethod<[string, string], undefined>,
  'deleteCircle' : ActorMethod<[string], undefined>,
  'deleteVibe' : ActorMethod<[bigint], undefined>,
  'getAllCircles' : ActorMethod<[], Array<[string, CircleView]>>,
  'getAllVibes' : ActorMethod<[], Array<Vibe>>,
  'getCallerProfile' : ActorMethod<[], Profile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCircleMembers' : ActorMethod<[string], Array<Principal>>,
  'getProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getUserVibes' : ActorMethod<[Principal], Array<Vibe>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinCircle' : ActorMethod<[string], undefined>,
  'leaveCircle' : ActorMethod<[string], undefined>,
  'postVibe' : ActorMethod<[string, string, string, [] | [string]], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'updateProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];